---
# DESCRIPTION
# Apply windows updates

- name: Apply windows updates
  hosts: all
  gather_facts: yes
     tasks:
      - name: check if reboot is required
        win_updates:
          category_names:
            - SecurityUpdates
            - CriticalUpdates
            - DefinitionUpdates
            - UpdateRollups
            - Updates
            - ServicePacks
        register: update_result
        check_mode: yes

      - name: pre-update reboot
        win_reboot:
          msg: "Reboot required before updates can be installed."
          reboot_timeout: 1200
        when: update_result.reboot_required or ansible_reboot_pending

 - name: Running Windows Update
      win_updates:
        category_names: ['SecurityUpdates','CriticalUpdates','UpdateRollups', 'Updates', 'DefinitionUpdates']
      register: result

    # output results
    - debug: var=result
    
    # reboot only if required
    - win_reboot:
      when: result.reboot_required
